---
- name: Terraform operations
  hosts: localhost
  gather_facts: false
  become: false

  environment:
    ARM_TENANT_ID: "{{ lookup('ansible.builtin.env', 'AZURE_TENANT') }}"
    ARM_SUBSCRIPTION_ID: "{{ lookup('ansible.builtin.env', 'AZURE_SUBSCRIPTION_ID') }}"
    ARM_CLIENT_ID: "{{ lookup('ansible.builtin.env', 'AZURE_CLIENT_ID') }}"
    ARM_CLIENT_SECRET: "{{ lookup('ansible.builtin.env', 'AZURE_SECRET') }}"

  vars:
    tf_project_dir: "{{ playbook_dir | dirname }}"
    tf_project_key: az_web_demo  # used for state key
    backend_conf: "{{ TF_BACKEND_CONFIG_FILE }}"  # this is assumed to be injected by a credential

  tasks:
    - name: Read backend config file
      slurp:
        src: {{ backend_conf }}
      register: backend_file_raw

    - name: Print backend config content
      debug:
        msg: "{{ backend_file_raw.content | b64decode }}"

    

  
  roles:
    - role: terraform_run
