---
- name: Create backend config file
  tempfile:
    state: file
    suffix: .tfbackend
  register: backend_file

- name: Write backend config content
  copy:
    content: "{{ backend_conf }}"
    dest: "{{ backend_file.path }}"

- name: Run terraform init
  command: >
    terraform init
    -backend-config="{{ backend_file.path }}"
    -input=false
  args:
    chdir: "{{ tf_project_dir }}"
  register: terraform_init

- name: Print terraform init output
  debug:
    var: terraform_init.stdout_lines
