---
- name: Configure web server
  hosts: tag_demo_web
  become: true

  vars_files:
    - vars/main.yml

  tasks:
    - name: Install httpd
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: Allow http traffic
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        zone: public

    - name: Create a custom index.html file
      ansible.builtin.template:
        dest: /var/www/html/index.html
        src: index.html.j2
