---
- name: Configure web server
  hosts: tag_demo_web

  tasks:
    - name: Install httpd
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    # - name: Create a custom index.html file
    #   ansible.builtin.copy:
    #     dest: /var/www/html/index.html
    #     content: |
    #       Enable SysAdmin Demo:
    #       Ansible Profiling with Callback Plugin
    #       Custom Web Page